#!/bin/bash
# -*- coding: utf-8 -*- vim: et noet ci pi sts=0 sw=4 ts=4
{
# TODO: Wider testing

function abort() {
exec 2>/dev/null
printf -- '\n'
exec >/dev/null
exit 130
}

trap -- 'abort' INT
set +H -u

exec {sleep_fd}<> <(:)
function sleep() {
read -t "${1:-"0"}" -r -u "${sleep_fd}"
}

function echo() {
printf -- '%s\n' "${@}"
}

function askauth() {
case "${user:-""}" in
	"")
		if ! read -p "Username: " -r "user"; then return 1; fi
		case "${user:-""}" in
			"")
				echo_err "auth: No username provided"
				exit 1
			;;
			?*) :;;
		esac
	;;
esac
case "${pass:-""}" in
	"")
		if ! read -p "Password: " -r -s "pass"; then echo; return 1; fi
		echo
		case "${pass:-""}" in
			"")
				echo_err "auth: No password provided"
				exit 1
			;;
			?*) :;;
		esac
	;;
esac
}

function echoauth() {
if sslchk "${1:-""}"; then
	printf -- '%s' "-u ${user}:${pass}"
fi
}

function echo_err() {
case "${2:-""}" in
	"")	printf -- '%s\n' "${name}: ${1:-"FAILED"}" 1>&2;;
	*)	printf -- '%s\n' "${name}: ${1:-"Unknown"}: ${2:-""}" 1>&2;;
esac
code=1
}

function mkconf() {
if ! [[ -d "${conf_dir}" ]]; then
	if ! mkdir -p -- "${conf_dir}"; then
		echo_err "${conf_dir}" "Failed to make the config directory"
		exit 1
	fi
fi
if ! [[ -e "${conf}" ]]; then
	if touch -- "${conf}" "${conf_aria2}"; then
		if ! mkconf_sec_set; then exit 1; fi
	else
		echo_err "${conf}" "Failed to make the config file"
		exit 1
	fi
fi
mkconf_sec
}

function mkconf_sec_set() {
if chown "${UID}:${GROUPS[0]}" -- "${2:-"${conf}"}"; then
	if ! chmod "${1:-"0600"}" -- "${2:-"${conf}"}"; then
		echo_err "${1}" "Cannot to set config${3:-" file"} permissions"
		return 1
	fi
else
	echo_err "${1}" "Failed to own the config${3:-" file"}"
	return 1
fi
}

function mkconf_sec() {
local "i"
if ! [[ -s "${conf}" ]]; then
	if ! askauth; then exit 1; fi
fi
if [[ -e "${conf}" ]]; then
	i=$( < "${conf}" )
	case "${i}" in
		""|":") if ! askauth; then exit 1; fi;;
	esac
else
	echo_err "${conf}" "Failed to find the config file"
	exit 1
fi
case "${i:-"x"}" in
	*?":"?*) return 0;;
	*)
		if mkconf_sec_set "0700" "${conf_dir}" " directory"; then
			if mkconf_sec_set; then
				printf -- '%s' "${user}:${pass}" > "${conf}"
			else
				exit 1
			fi
			if mkconf_sec_set "0600" "${conf_aria2}" " file (aria2c)"; then
				printf -- '%s\n' "http-user=${user}" "http-passwd=${pass}" > "${conf_aria2}"
				return 0
			fi
		else
			exit 1
		fi
	;;
esac
}

function auth_zero() {
local "i"
if [[ -s "${conf}" ]]; then
	if ! read -p "Are you sure? (y/N) " -r "i"; then exit 1; fi
	case "${i:-""}" in
		[yY][eE][sS]|[yY]) :;; *) exit 1;;
	esac
	if ! rm -- "${conf}"; then code=1; fi
	if [[ -s "${conf_aria2}" ]]; then
		if ! rm -- "${conf_aria2}"; then code=1; fi
	fi
else
	exit 0
fi

rmdir -- "${conf_dir}" 2>/dev/null
case "${code:-"0"}" in
	0)
		echo_err "auth reset: successfully reset username/password"; exit 0;;
	1)
		echo_err "auth reset: failed to reset username/password"; exit 1;;
esac
exit 1
}

function authset() {
local "i"
case "${user:-":"}:${pass:-":"}" in
	":::") :;;
	*"::"*) show_help 1 1>&2;;
	*?":"?*) return 0;;
esac
if [[ -s "${conf}" ]]; then
	i=$( < "${conf}" )
	user="${i%%":"*}"
	pass="${i#*":"}"
else
	echo_err "${conf}" "No config file found"
	exit 1
fi
}

function sslchk() {
case "${1:-"${cdn:-""}"}" in
	"https://"?*) return 0;;
	*)
		echo_err "${1:-"${cdn:-""}"}" "Is not using SSL"
		exit 1
	;;
esac
}

function lsget_grep() {
local "i"
while read -r i; do
	case "${i}" in
		*"${m%%"|"*}"*|*"${m##*"|"}"*) echo "${i}";;
	esac
done
}

function lsget() {
local "m" "i" "old_i" "type" "no_repeat"
no_repeat=""
m='<span class="filename">|<div class="title">'
while read -r i; do
	i="${i%"</span>"*}"
	i="${i%%" Included</div>"*}"
	i="${i##*">"}"
	case "${no_repeat:-"<.>"}" in *"<:>${i}<:>"*) continue;; esac
	case "${i:-"###"}" in
		"${gg_i}"|"${gg_g}") type="downloads"; continue;;
		"${gg_p}") type="patches"; continue;;
		"${old_i:-"@@@"}") continue;;
		*";"*) i="${i//"&#039;"/"'"}"; i="${i//"&amp;"/"&"}";;
	esac
	case "${type:-"downloads"}|${i}" in
		"patches|"[pP][aA][tT][cC][hH]"_"*"."[eE][xX][eE]|"patches|"[pP][aA][tT][cC][hH]"_"*"."[bB][iI][nN])
			case "${always_include}" in
				*" ${i} "*) echo "${cdn}/${type:-"downloads"}/${ref##*"/"}/${i}";;
				*) continue;;
			esac
		;;
		"downloads|"*)
			echo "${cdn}/downloads/${ref##*"/"}/${i}"
		;;
		"patches|"*)
			echo "${cdn}/patches/${i}"
		;;
	esac
	old_i="${i}"
done < <( curl --tlsv1.3 --user-agent "${agent}" --referer "${ref}" --silent --output - -- "${1}" | lsget_grep )
echo "END"
}

function cdget_set_meta() {
local "meta"
meta=$( echoauth "${1:-"http://example.com"}" | curl --tlsv1.3 -A "${agent}" -I -s -K- -- "${1:-""}" 2>&1 )
case "${meta}" in
	"HTTP/2 404"*)
		echo_err "${1##*"/"}" "No such CDN file"
		return 1
	;;
	"HTTP/2 200"*)
		:
	;;
	"HTTP/2 401"*)
		echo_err "${1##*"/"}" "Incorrect username/password"
		no_meta_permission=1
		return 1
	;;
	*)
		echo_err "${1##*"/"}" "An unknown CDN error"
		return 1
	;;
esac
meta="${meta#*"content-length: "}"
meta="${meta%%"etag: "*}"
size="${meta%%?"
"*}"
date="${meta#*"last-modified: "}"
date="${date%%?"
"*}"
date=$( date -d "${date}" -- "+%Y%m%d%H%M.%S" 2>/dev/null )
}

function cdget_no_space() {
local "free"
free=$( df --block-size=1 --output=avail -- "${PWD}" 2>/dev/null )
free="${free##*"Avail"?}"
free=$(( free - 33554432 ))
if [[ "${free}" -lt "${size:-"0"}" ]]; then
	echo "${1:-"unknown"}: No free space to download"
	echo "${1##*"/"}: FAILED"
	return 1
fi
}

function cdnget_local_sfv() {
local "date" "size" "i"
case "${global_path:-""}" in "") return 1;; esac
if cdget_set_meta "${cdn}/sfv/${global_path%"/"}.sfv" 2>/dev/null; then
	local_sfv=$(
			while read -r i; do
				echo "${global_path}${i}"
			done < <( echoauth | curl --tlsv1.3 -A "${agent}" -s -K- -- "${cdn}/sfv/${global_path%"/"}.sfv" )
		)
	case "${local_sfv}" in
		*?"/"?*"  "????????*) return 0;;
		*) unset -- "local_sfv"; return 1
	esac
else
	return 1
fi
}

function cdnget() {
local "date" "size" "final_size" "c" "file" "local_sfv" "skip_sfv"
c=0
file="${cdnget_path:-""}${1##*"/"}"
if [[ -s "${file}" ]]; then
	return 0
fi
if sslchk "${1:-"http://example.com"}"; then
	if ! [[ -s "${conf_aria2}" ]]; then
		opt_www="curl"
	fi
	cdget_set_meta "${1}"
	case "${no_meta_permission:-"0"}" in 1) echo "${file}: FAILED"; return 1;; esac
	if ! cdget_no_space "${file}"; then return 1; fi
	( echo_err "downloading" "${file}"; )
	case "${opt_www:-"curl"}" in
		"curl")
			if [[ -e "${file}.part.aria2" ]]; then
				rm -f -- "${file}.part" "${file}.part.aria2" 2>/dev/null
			fi
			until echoauth "${1:-"http://example.com"}" | curl --tlsv1.3 -C- -K- --connect-timeout 60 --user-agent "${agent}" --referer "${ref}" --progress-bar --output "${file}.part" -- "${1}" 1>&2; do :; done
		;;
		"aria2c")
			if aria2c --min-tls-version=TLSv1.3 --continue=true --http-auth-challenge=true --conf-path="${conf_aria2}" --no-netrc=true --max-connection-per-server=4 --max-file-not-found=1 --max-tries=0 --timeout=60 --user-agent="${agent}" --referer="${ref}" --enable-color=false --log-level=error --console-log-level=error --summary-interval=0 --download-result=hide --out="${file}.part" -- "${1}" 1>&2; then
				echo
			else
				echo "${file}: FAILED"; return 1
			fi
		;;
	esac
else
	return 1
fi
until ! [[ -e "${file}.aria2" ]]; do
	sleep 1
	(( c++))
	case "${c:-"0"}" in 10) break;; esac
done
case "${size:-"0"}" in
	0) :;;
	*)
		final_size=$( stat --printf='%s' -- "${file}.part" 2>/dev/null )
		case "${final_size:-"x"}" in
			"${size:-"y"}")
				if ! mv -- "${file}.part" "${file}"; then
					return 1
				fi
				case "${opt_crc:-"0"}|${file}" in
					1"|"?*"."[sS][fF][vV]) :;;
					1"|"?*)
							case "${opt_pe32:-"0"}" in
								0) :;;
								1"|"?*"."[eE][xX][eE])
									skip_sfv=1
									if ! process_exe_pe "${file}"; then
										echo_err "${file}" "PE checksum does not match"
										echo "${file}: FAILED"; return 1
									fi
								;;
							esac
							case "${skip_sfv:-"0"}" in
								1) unset -- "skip_sfv";;
								*)
									final_sfv=$( process_make_crc "${file}" )
									case "${file}" in
										*"/"*) :;;
										*) final_sfv="${global_path:-"?/"}${final_sfv}"
									esac
									case "${local_sfv:-"${global_sfv:-"${final_sfv%"  "*}"}"}" in
										*"${final_sfv%"  "*}"*)
											case "${local_sfv:-"${global_sfv:-"${final_sfv}"}"}" in
												*"${final_sfv}"*) :;;
													*)
													echo_err "${file}" "CRC32 checksum does not match"
													echo "${file}: FAILED"; return 1
												;;
											esac
										;;
									esac
								;;
							esac
					;;
				esac
				case "${opt_ggchk:-"0"}" in
					0) echo "${file}: OK";;
				esac
			;;
			*)
				cho_err "${file}" "Filesize does not match"
				echo "${file}: FAILED"; return 1
			;;
		esac
	;;
esac
case "${date:-"0"}" in
	0) :;;
	????????????"."??) touch -mt "${date}" -- "${file}" 2>/dev/null;;
esac
case "${opt_xattr:-"0"}" in
	1)
		setfattr -n "user.xdg.referrer.url" -v "${ref:-"${www}"}" -- "${file}" 2>/dev/null
		setfattr -n "user.xdg.origin.url" -v "${1:-"${cdn}"}" -- "${file}" 2>/dev/null
	;;
esac
return 0
}

function logchk() {
local "i"
if type "nslookup" >/dev/null; then
	i=$( nslookup "${cdn#*"//"}" "1.1.1.1" 2>/dev/null )
	case "${i:-""}" in
		*"*** Can't find"*|*"** server can't find "*) echo_err "auth" "An incorrect CDN address"; return 1;;
		*"Name:	${cdn#*"//"}"*) :;;
		*) echo_err "auth" "No Internet connection"; return 1;;
	esac
fi
i=$( echoauth | curl --tlsv1.3 -A "${agent}" -I -s -w "########%{http_code}" -K- -- "${cdn}/auth/authorize" )
case "${i:-""}" in
	*"########200"|*"########404")
		case "${opt_chk_auth:-"0"}" in
			1) echo_err "auth: Successful log-in"; exit 0;;
			*) return 0;;
		esac
	;;
	*"########401") echo_err "auth" "Incorrect username/password"; return 1;;
	*"########403") echo_err "auth" "Cannot find the log-in page on ${gg_name} CDN"; return 1;;
	*"########503") echo_err "auth" "Multiple log-ins are not allowed"; return 1;;
	*"########521") echo_err "auth" "${gg_name} CDN is offline"; print_notice; return 1;;
	*) echo_err "auth" "Cannot contact ${gg_name} CDN"; return 1;;
esac
}

function pkgchk() {
if type "aria2c" &>/dev/null; then
	opt_www="aria2c"
else
	opt_www="curl"
fi
if ! type "b2sum" "${@}" "${opt_www:-"curl"}" &>/dev/null; then
	printf -- '%s\n' "${name}: please install: coreutils ${*}" 1>&2
	exit 1
fi
if type "7z" "tar" &>/dev/null; then
	opt_crc=1
fi
if type "ggchk" &>/dev/null; then
	opt_ggchk=1
fi
if type "setfattr" &>/dev/null; then
	opt_xattr=1
fi
if type "python3" &>/dev/null; then
	opt_pe32=1
fi
}

function rmslash_arg() {
case "${arg:-""}" in
	*"/")
		arg="${arg/%"/"}"
	;;
esac
}

function is_gg() {
case "${1}" in
	"${www}/game/"?*"/"?*|"${cdn}/sfv/"?*"/"?*|"${cdn}/"?*"/"?*"/"?*"/"?*)
		return 1
	;;
	"${www}/game/"?*|"${cdn}/sfv/"?*|"${cdn}/"?*"/"?*"/"?*) return 0;;
	"${www}/"?*|"${cdn}/"?*)
		echo_err "${1}" "Is not a ${gg_name} download link"
		return 1
	;;
	"http://${www#*"https://"}/game/"?*|"http://${cdn#*"https://"}/"?*"/"?*)
		arg="https://${1#*"http://"}"
		return 0
	;;
	"${www#*"https://"}/game/"?*|"${cdn#*"https://"}/"?*"/"?*)
		arg="https://${1}"
		return 0
	;;
	"http://"?*|"https://"?*)
		echo_err "${1}" "Is not ${gg_name}"
		return 1
	;;
esac
case "${1}" in
	[0123456789]|10|[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9])
		echo_err "${1}" "GOG IDs are not supported"
		return 1
	;;
	[0-9a-z]*)
		case "${1}" in
			"${1//[^0-9a-z\-_]}")
				arg="${www}/game/${1}"
				return 0
			;;
		esac
	;;
	*)
		echo_err "${1}" "Is not ${gg_name}"
		return 1
	;;
esac
return 1
}

function is_file() {
case "${1:-""}" in
	*)
		if [[ -d "${1}" ]]; then
			echo_err "${1}" "Is a directory"
		elif [[ -e "${1}" ]]; then
			if [[ -r "${1}" ]]; then
				return 0
			else
				echo_err "${1}" "Permission denied"
			fi
		else
			echo_err "${1}" "No such file or directory"
		fi
	;;
esac
return 1
}

function show_help() {
printf -- '%s\n' "Usage: ${name:-"${0##*"/"}"} [OPTION]... [URL/SLUG]...
Download files from ${gg_name} CDN.

  -u [USERNAME]  set your ${gg_name} CDN username
  -p [PASSWORD]  set your ${gg_name} CDN password
      --reset    reset username/password config
  -w [ADDRESS]   set the ${gg_name} address
  -a, --auth     check authentification and exit
  -n, --no-dir   do not put files in a subdirectory
  -l, --latest   list added/updated on ${gg_name} CDN
  -L, --Latest   list slugs of added/updated on ${gg_name} CDN
  -s, --sfv      update offline SFV database
  -h, --help     display this help and exit"
exit "${1:-"0"}"
}

function process_slug() {
case "${1:-""}" in
	"${cdn}/patches/"?*)
		global_path=""
		unset -- "cdnget_path"
		return 1
	;;
	"${cdn}/downloads/"?*"/"?*)
		cdnget_path="${1#*"${cdn}/downloads/"}"
		cdnget_path="${cdnget_path#*"${cdn}/patches/"}"
		cdnget_path="${cdnget_path%%"/"*}"
		cdnget_path="${cdnget_path:-"unknown"}/"
		global_path="${cdnget_path}"
		case "${opt_no_dir:-"0"}" in
			1) unset -- "cdnget_path";;
		esac
		return 1
	;;
	"${cdn}/sfv/"?*"."[sS][fF][vV])
		cdnget_path="${1##*"/"}"
		cdnget_path="${cdnget_path%"."[sS][fF][vV]*}"
		cdnget_path="${cdnget_path:-"unknown"}/"
		global_path="${cdnget_path}"
		case "${opt_no_dir:-"0"}" in
			1) unset -- "cdnget_path";;
		esac
		return 1
	;;
	"${www}/game/"?*"/"?*|"${cdn}/"?*) return 1;;
	"${www}/game/"?*|"${www}/game/"?*"/")
		cdnget_path="${1#*"${www}/game/"}"
		cdnget_path="${cdnget_path%%"/"*}"
		cdnget_path="${cdnget_path:-"unknown"}/"
		global_path="${cdnget_path}"
		case "${opt_no_dir:-"0"}" in
			1) unset -- "cdnget_path"; return 0;;
		esac
		case "${PWD##*"/"}/" in
			"${cdnget_path}") unset -- "cdnget_path"; return 0;;
		esac
		if ! [[ -d "${cdnget_path}" ]]; then
			if ! mkdir -p -- "${cdnget_path}"; then
				echo_err "${1}" "FAILED"
			fi
		fi
	;;
esac
}

function process_list_ggchk() {
local "i"
case "${opt_ggchk:-"0"}" in 0) return 0;; esac
case "${list:-""}" in
	"") echo_err "${gg_name}" "No filelist found"; code=1; return 1;;
esac
while read -r i; do
	case "${i}" in
		"${gg_i}"|"${gg_p}"|"${gg_g}") continue;;
		"END") return "${func_code:-"0"}";;
	esac
	if ! ggchk "${cdnget_path:-""}${i##*"/"}"; then func_code=1; fi
done < <( echo "${list}" )
}

function process_list() {
local "i"
case "${list:-""}" in
	"") echo_err "${gg_name}" "No filelist found"; code=1; return 1;;
esac
while read -r i; do
	case "${i}" in
		"${gg_i}"|"${gg_p}"|"${gg_g}") continue;;
		"END") return "${func_code:-"0"}";;
	esac
	if ! cdnget "${i}"; then func_code=1; fi
done < <( echo "${list}" )
}

function process() {
local "list" "cdnget_path" "global_path" "local_sfv"
unset -- "arg"
if process_slug "${1}"; then
	list=$( lsget "${1}" )
	case "${list:-""}" in
		"END")
			echo_err "${1##*"/"}" "No game files found"
			echo "${1##*"/"}: FAILED"
			return 1
		;;
	esac
	cdnget_local_sfv
	case "${no_meta_permission:-"0"}" in
		1)
			echo "${1##*"/"}: FAILED"
			return 1
		;;
	esac
	if process_list; then
		if ! process_list_ggchk; then
			code=1; return 1
		fi
	else
		code=1; return 1
	fi
else
	cdnget_local_sfv
	case "${no_meta_permission:-"0"}" in
		1) echo "${1##*"/"}: FAILED"
			return 1
		;;
	esac
 	if ! cdnget "${1}"; then code=1; return 1; fi
	case "${opt_ggchk:-"0"}" in
		1) if ! ggchk "${cdnget_path:-""}${1##*"/"}"; then code=1; return 1; fi;;
	esac
fi
}

function process_make_crc() {
local "i"
if ! i=$( 7z h -scrcCRC"${mode:-"32"}" -bb0 -bd -si -ba < "${1:-"/dev/stdin"}" 2>/dev/null ); then
	return 1
fi
i="${i:-""}"
i="${i%%" "*}"
i="${i,,}"
echo "${1:-"-"}  ${i}"
}

function process_crc_main() {
case "${opt_crc:-"0"}" in
	0)
		printf -- '%s\n' "${name}: please install: 7z" 1>&2
		exit 1
	;;
esac
for i in "${@}"; do
	if is_file "${i}"; then
		process_make_crc "${i}"
	else
		code=1
	fi
done
exit "${code:-"0"}"
}

function sfvchk() {
case "${opt_crc:-"0"}" in 0) return 0;; esac
if [[ -s "${conf_sfv}" ]]; then
	if ! gzip --test -- "${conf_sfv}" &>/dev/null; then
		rm -f -- "${conf_sfv}" 2>/dev/null
	fi
fi
}

function sfv_to_ram() {
case "${opt_crc:-"0"}" in 0) return 0;; esac
if [[ -s "${conf_sfv}" ]]; then
	global_sfv=$( tar -xf "${conf_sfv}" -O --wildcards --no-anchored '*.[sS][fF][vV]' )
fi
}

function sfvget() {
local "i"
case "${opt_crc:-"0"}" in 0) return 0;; esac
( echo_err "downloading" "${conf_sfv##*"/"}"; )
case "${opt_sfv:-"0"}" in
	1)
		sfv_base="${sfv_base##*"_if/"}"
	;;
esac
if curl --tlsv1.3 --connect-timeout 60 --user-agent "${agent}" --referer "${sfv_base#*"if_/"}" --progress-bar --output "${conf_sfv}" -- "${sfv_base:-""}"; then
	i=$( sha256sum -- "${conf_sfv}" )
	case "${opt_sfv:-"0"}" in
		1)
			sfv_base_sha="${i%%"  "*}"
		;;
	esac
	case "${i%%"  "*}" in
		"${sfv_base_sha:-""}")
			if mkconf_sec_set "0600" "${conf_sfv}" " file (SFV)"; then
				if gzip --test -- "${conf_sfv}" &>/dev/null; then
					echo "${name}: ${conf_sfv##*"/"}: OK" 1>&2
					return 0
				else
					rm -f -- "${conf_sfv}"
					echo "${name}: ${conf_sfv##*"/"}: FAILED" 1>&2
				fi
			else
				echo "${name}: ${conf_sfv##*"/"}: FAILED" 1>&2
				return 1
			fi
		;;
		*)
			rm -f -- "${conf_sfv}"
			echo_err "${conf_sfv##*"/"}: The web archive is corrupted"
			echo "${name}: ${conf_sfv##*"/"}: FAILED" 1>&2
			return 1
		;;
	esac
fi
}

function set_auth_opt() {
case "${OPT:-""}" in
	u)
		case "${OPTARG:-""}" in
			"") echo_err "auth: No username provided"; exit 1;;
			"-"*) show_help 1 1>&2;;
			*) user="${OPTARG}";;
		esac

	;;
	p)
		case "${OPTARG:-""}" in
			"") echo_err "auth: No password provided"; exit 1;;
			"-"*) show_help 1 1>&2;;
			*) pass="${OPTARG}";;
		esac
	;;
	*) exit 1;;
esac
}

function set_www_opt() {
case "${OPTARG:-""}" in
	"") echo_err "CDN: No address provided"; exit 1;;
	"-"*) show_help 1 1>&2;;
	*)
		www="${OPTARG}"
		case "${www}" in
			"ftp://"?*)
				www="${www/#"ftp://"}"
			;;
			"ftps://"?*)
				www="${www/#"ftps://"}"
			;;
			"sftp://"?*)
				www="${www/#"sftp://"}"
			;;
			"http://"?*)
				www="${www/#"http://"}"
			;;
			"https://"?*)
				www="${www/#"https://"}"
			;;
		esac
		case "${www}" in
			"www."?*)
				www="${www/#"www."}"
			;;
			"cdn."?*)
				www="${www/#"cdn."}"
			;;
		esac
		www="${www%%"/"*}"
	;;
esac
cdn="https://cdn.${www#*"//"}"
}

function process_exe_pe() {
local "pe_old" "pe" "script" "excl_pe"
case "${1##*"/"}" in
	"setup_colin2005.exe") excl_pe="27D82900";;
	"setup_obscure.exe") excl_pe="E1D42200";;
	"setup_republic_the_revolution.exe") excl_pe="801FFA2B";;
	"setup_toca_3.exe") excl_pe="AA452800";;
esac
script="#!/usr/bin/env python3
# -*- coding: utf-8 -*- vim: et noet ci pi sts=0 sw=4 ts=4

from __future__ import print_function
import sys
sys.tracebacklimit = 0
import os, io, argparse, re, struct
from io import DEFAULT_BUFFER_SIZE as DEFAULT

CODE = 0

def pe_make(FILENAME):
	SKIP = 344
	PE = 0
	READ = False
	PE_OLD = str(\"00000000\")
	with open(FILENAME, 'rb') as openfile:
		while True:
			DATA = openfile.read(DEFAULT)
			LEFT = len(DATA) % 4
			MAX = len(DATA) + ((4-LEFT) * ( LEFT != 0 ))
			if not DATA:
				break

			for i in range( int(MAX / 4) ):
				if READ == False:
					if i == int(SKIP / 4):
						READ = True
						PE_OLD = DATA[344:348].hex().upper()
						continue
				if i+1 == (int(MAX / 4)) and LEFT:
					line = struct.unpack('I', DATA[i*4:]+ (b'\0' * (4-LEFT)) )[0]
				else:
					line = struct.unpack('I', DATA[ i*4 : i*4+4 ])[0]
				PE += line
				if PE >= 2**32:
					PE = (PE & 0xffffffff) + (PE >> 32)


		PE = (PE & 0xffff) + (PE >> 16)
		PE = (PE) + (PE >> 16)
		PE = PE & 0xffff

		PE = PE + os.path.getsize(FILENAME)
		PE = '%08X' % (PE & 0xffffffff)
		PE_HASH = PE[6:8] + PE[4:6] + PE[2:4] + PE[0:2]
		return PE_HASH, PE_OLD

if __name__ == '__main__':
	try:
		parser = argparse.ArgumentParser(
				description='Check PE (32-bit) checksums of GOG installers.')

		parser.add_argument('EXE', action='store', nargs='*')
		args = parser.parse_args()

		for ARG in args.EXE:
			PE, PE_OLD = pe_make(ARG)
			print(PE + \"=\" + PE_OLD)
			if PE == PE_OLD:
				sys.exit(0)
			else:
				sys.exit(1)

	except KeyboardInterrupt:
		sys.stderr.close()
		print ('')
		sys.stdout.close()
		sys.exit(130)

	except BrokenPipeError:
		sys.stderr.close()
		sys.stdout.close()
		sys.exit(1)

sys.exit(CODE)"
pe=$( echo "${script}" | python3 -- "/dev/stdin" -- "${1:-"/dev/zero"}" )
pe_old="${pe#*"="}"
pe="${pe%"="*}"
case "${excl_pe:-"${pe_old:-"x"}"}" in
	"${pe:-"x"}") return 0;;
	*) code=1; return 1;;
esac
}

function print_notice_fetch_grep() {
local "i" "i_on"
while read -r i; do
	case "${i}" in
		*'<div id="notice">'*)
		i_on=1
		;;
	esac
	case "${i_on:-"0"}" in
		1) echo "${i}";;
	esac
done
}

function print_notice_fetch() {
local "i"
while read -r i; do
	case "${i}" in
		"<div id=\"notice\">") continue;;
		"<span class=\"txt-red\">"*) :;;
		"</div>"|"<div class=\""*|"<form "*|"<button "*|"<h1>"*|"<a class="*)
			break
		;;
	esac
	while true; do
		case "${i:-""}" in
			"") return 1;;
			"<"*) i="${i#*">"}";;
			*"</"*) i="${i%"</"*}";;
			?*) break;;
			*) return 1;;
		esac
	done
	i="${i//[^[:print:]]}"
	i="${i//'"'/"'"}"
	i="\"${i}\""
	case "${i:-""}" in
		"") return 1;;
		*) echo "${i}";;
	esac
done < <( curl --tlsv1.3 --user-agent "${agent}" --referer "${ref:-"${www}"}" --silent --output - -- "${www}" 2>/dev/null | print_notice_fetch_grep )
return 0
}

function print_notice() {
local "i"
if ! i=$( print_notice_fetch ); then return 1; fi
case "${i:-""}" in
	"") return 1;;
	*)
		echo_err "notice" "${i}"
	;;
esac
}

function print_latest_fetch_grep() {
local "i" "i_on"
while read -r i; do
	case "${i}" in
		*'<lastBuildDate>'*)
		i_on=1
		;;
	esac
	case "${i_on:-"0"}" in
		1) echo "${i}";;
	esac
done
}

function print_latest_fetch() {
local "i" "title" "date" "slug" "c"
title=()
date=()
slug=()
while read -r i; do
	case "${i}" in
		"<lastBuildDate>"?*|"<docs>"?*|"<media:"?*|"<enclosure "?*|"<guid "?*|"</item>"|"<item>") continue;;
		"<title>"?*)
			i="${i/#"<title>"}"
			i="${i/%"</title>"}"
			i="${i//"&#039;"/"'"}"
			i="${i//"&amp;"/"&"}"
			i="${i//'"'/"'"}"
			title+=( "${i}" )
		;;
		"<pubDate>"?*)
			i="${i/#"<pubDate>"}"
			i="${i/%"</pubDate>"}"
			case "${i}" in
				[A-Z][a-z][a-z]" "[0-9]*","[0-9][0-9][0-9][0-9]" "[0-9][0-9]":"[0-9][0-9])
					i="${i} GMT"
				;;
				[A-Z][a-z][a-z]" "[0-9]*","[0-9][0-9][0-9][0-9]" "[0-9][0-9]":"[0-9][0-9])
					i="${i} GMT"
				;;
			esac
			i=$( date -d "${i:-"now"}" -- "+%+4Y-%m-%d" 2>/dev/null )
			date+=( "${i}" )
		;;
		"<link>"?*)
			i="${i/#"<link>${www}/game/"}"
			i="${i/%"</link>"}"
			slug+=( "${i}" )
		;;
		"</channel>"|"</rss>")
      		break
		;;
		*) continue;;
	esac
	while true; do
		case "${i:-""}" in
			"") return 1;;
			"<"*) i="${i#*">"}";;
			*"</"*) i="${i%"</"*}";;
			?*) break;;
			*) return 1;;
		esac
	done
	i="${i//[^[:print:]]}"
	case "${i:-""}" in
		"")continue;;
	esac
done < <( curl --tlsv1.3 --user-agent "${agent}" --referer "${ref:-"${www}"}" --silent --output - -- "${www}/rss" 2>/dev/null | print_latest_fetch_grep )
c=0
if type tput &>/dev/null; then
	m=$( tput lines 2>/dev/null )
	((m--))
fi
for i in "${title[@]}"; do
	case "${opt_slug:-"0"}" in
		1) echo "${slug[$c]:-"unknown"}";;
		*) echo "${date[$c]:-"Unknown"} \"${title[$c]:-"Unknown Title"}\"";;
	esac
	((c++))
	case "${c:-"x"}" in
		"${m:-"y"}") break;;
	esac
done
return 0
}

function print_latest() {
local "i"
if ! i=$( print_latest_fetch ); then return 1; fi
case "${i:-""}" in
	"") return 1;;
	*)
		echo "${i}"
	;;
esac
}


function main() {
local "name" "gg_name" "gg_i" "gg_p" "gg_g" "www" "cdn" "conf_dir" "conf" "conf_aria2" "agent" "conf_sfv" "LANG" "LC_ALL" "OPTERR" "OPTIND" "OPT" "OPTARG" "opt_www" "opt_ggchk" "opt_slug" "global_sfv" "arg" "code"
LANG=C
LC_ALL=C
export "LANG" "LC_ALL"
OPTERR=0
OPTIND=1
name="${0##*"/"}"
gg_name="GOG Games"
gg_i="Game Items"
gg_p="Patch/Other Items"
gg_g="Goodies"
www="https://gog-games.com"
cdn="https://cdn.${www#*"//"}"
conf_dir="${HOME}/.local/share/ggcdn"
conf="${conf_dir}/id_gg"
conf_aria2="${conf_dir}/aria2.conf"
agent='GOG-Downloader (InDev)'
sfv_base="https://web.archive.org/web/20220827203612_if/https://codeload.github.com/GOG-Games-com/GOG.com-Game-Collection-Verification/tar.gz/refs/heads/main"
sfv_base_sha="b62a0dd74dfaf5a073a0cd279200dc4b1d4fc80e4ed8a9700ea1bd8aa9251ec1"
conf_sfv="${conf_dir}/sfv.tgz"
always_include=" patch_biomutant_1.3_(49718)_to_1.4_(51251).exe
 patch_caribbean_2.4.1.10.exe
 patch_dark_matter_2.0.1.4.exe
 patch_dragon_age_origins_ultimate_2.1.1.5.exe
 patch_giana_sisters_rise_of_the_owlverlord_2.1.1.9.exe
 patch_knock-knock_2.0.1.5.exe
 patch_planetbase_1.3.7_(38217)_to_1.3.8_(45490).exe
 patch_sr2_lang_selection_hotfix.exe
 patch_speedball_2_hd_2.0.2.4.exe
 patch_subject_13_2.0.1.2.exe
 patch_super_time_force_ultra_2.0.1.2.exe
 patch_slop_episode1_2.0.1.2.exe
 patch_slop_episode2_2.0.1.2.exe
 patch_slop_episode3_2.0.1.2.exe
 patch_the_guild2_pirates_2.0.1.5.exe
 patch_the_witcher_3_wild_hunt_-_game_of_the_year_edition_1.31_(A)_to_1.32.exe "
pkgchk "curl" # "python3" "nslookup" "ggchk" "aria2c" "7z" "gzip" "tar" "xattr"
while getopts ":-:p:u:w:anlLh" "OPT"; do
	case "${OPT}" in
		-)
			case "${OPTARG}" in
				a|auth|authentification) opt_chk_auth=1;;
				n|no-dir|no-directory|no-folder) opt_no_dir=1;;
				sfv) opt_sfv=1;;
				reset) auth_zero;;
				l|list|latest|list-latest|latest-list) print_latest_fetch;;
				L|List|Latest|List-[lL]atest|Latest-[lL]ist) opt_slug=1; print_latest_fetch;;
				h|help) show_help;;
				*) show_help 1 1>&2;;
			esac
		;;
		u) set_auth_opt;;
		p) set_auth_opt;;
		w) set_www_opt;;
		a) opt_chk_auth=1;;
		n) opt_no_dir=1;;
		l) print_latest_fetch;;
		L) opt_slug=1; print_latest_fetch;;
		h) show_help;;
		*) show_help 1 1>&2;;
	esac
done
shift $(( OPTIND - 1 ))
unset -- "OPT" "OPTARG"
OPTERR=1
OPTIND=1
case "${0##*"/"}" in
	crc32) process_crc_main "${@}"; exit 1;;
	crc64) mode=64; process_crc_main "${@}"; exit 1;;
esac
mkconf
sfvchk
case "${opt_sfv:-"0"}" in
	1) if ! sfvget; then exit 1; fi;;
	*)
		if ! [[ -s "${conf_sfv}" ]]; then
			if ! sfvget; then exit 1; fi
		fi
	;;
esac
unset -- "sfv_base" "sfv_base_sha"
case "${opt_chk_auth:-"0"},${#}" in 0,0) exit 0;; 0,*) sfv_to_ram;; esac
authset; sslchk
if ! logchk; then exit 1; fi
for arg in "${@}"; do
	rmslash_arg
	if is_gg "${arg}"; then
		ref="${arg}"
		process "${arg}"
	else
		code=1
	fi
done
exit "${code:-"0"}"
}

main "${@}"
exit 1
}
